// src/main/svelte/Navbar.svelte
<script>
  import {
    Container,
    Nav,
    Navbar,
    NavbarBrand,
    NavItem,
    NavLink
  } from 'sveltestrap';

  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
</script>

<Navbar light expand="sm">
  <Container>
    <NavbarBrand href="/">readme app</NavbarBrand>
    <Nav class="ml-auto" navbar>
      <NavItem>
      <!-- overview -->
        <NavLink href="#" on:click={() => dispatch('menu', '')}>Home</NavLink>
      </NavItem>
      <NavItem>
        <!-- /editor -->
        <NavLink href="#" on:click={() => dispatch('menu', 'editor')}>New</NavLink>
      </NavItem>
      <NavItem>
        <!-- /login -->
        <NavLink href="/oauth2/authorization/github" title="Login with GitHub">Sign in</NavLink>
      </NavItem>
      <NavItem>
        <!-- /logout -->
        <NavLink href="/logout">Logout</NavLink>
      </NavItem>      
      <NavItem>
        <!-- /user -->
        <NavLink href="#" on:click={() => dispatch('menu', 'user')}>User</NavLink>
      </NavItem>
    </Nav>
  </Container>
</Navbar>

// angular/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import {AuthenticationService, User} from "@app/security";

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  user: User;
  activeId = 1;

  constructor(private authenticationService: AuthenticationService) {
    this.authenticationService.user.subscribe(x => this.user = x);
  }

  ngOnInit(): void {
  }

  logout() {
    this.authenticationService.logout();
  }

}

<nav class="navbar navbar-light bg-light navbar-expand-sm">
  <div class="container">
    <a class="navbar-brand" href="/">readme app</a>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul ngbNav [(activeId)]="activeId" class="ml-auto">
        <li [ngbNavItem]="1">
          <a ngbNavLink>New</a>
        </li>

        <li [ngbNavItem]="2">
          <a ngbNavLink (click)="logout()">Logout</a>
        </li>

        <li [ngbNavItem]="3">
          <a ngbNavLink title="basic Login">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
